version: '3'

services:
  qr-scanner:
    build: 
      context: .
      dockerfile: Dockerfile
    image: qr-scanner-server:latest
    container_name: qr-scanner-server
    ports:
      - "8443:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "--spider", "https://localhost:3000"]
      interval: 30s
      timeout: 3s
      retries: 3
